#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "heisenbridge"
name = "Heisenbridge"
description.en = "A bouncer-style Matrix-IRC bridge"
description.fr = "Une passerelle Matrix-IRC de style bouncer"

version = "1.14.5~ynh1"

maintainers = ["Salamandar"]

[upstream]
license = "MIT"
userdoc = "https://yunohost.org/apps"
code = "https://github.com/hifi/heisenbridge"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]


[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.apt]
    packages = [
        "python3"
    ]
